### ISSUE TITLE
Probleme durch Search&Replace: {} > Tilde

### ISSUE THREAD

**Issue by chrdoe** [langsci/212#1282]
bei überflüssigen {} in Tabellen, die du mit einer Tilde ersetzt hast, führt das zu dem unerwünschten Effekt, daß es doppelte oder zu breite Leerzeichen gibt. Ich habe das geändert, wo ich oder die Proofreader es gesehen haben. Das ging dann nur dadurch, daß ich einige Tilden wieder mit {} ersetzt habe. Betrifft vor allem Abbreviations, nach denen einen {} gesetzt werden musste, weil sonst gar kein Leerzeichen entsteht. 

Zum Beispiel:
\Pl X > kein Leerzeichen zwischen PL und X
\Pl{} X > ein Leerzeichen zwischen PL und X
\Pl~ X > zuviel Leerzeichen zwischen PL und X

**Comment by Glottotopia** [comment]
bei solchen Sachen besser "{\Pl}" als "\Pl " oder "\PL{}". Dann werden keine Leerzeichen gefressen.

**Comment by chrdoe** [comment]
Okay, hab ich ersetzt durch, zum Beispiel {\Sg}
