### ISSUE TITLE
Tabellenfussnoten

### ISSUE THREAD

**Issue by chrdoe** [langsci/212#1283]
nach lspbottomrule erscheint häufig eine weitere Linie, wenn es eine Fussnote in der Tabelle gibt

**Comment by Glottotopia** [comment]
Das wollte denke ich @haspelmath so

**Comment by haspelmath** [comment]
Ist nicht wichtig.

**Comment by chrdoe** [comment]
Okay, ich hab die Fussnoten bei einigen Tabellen zur Reference im Fließtext verschoben oder ganz rausgenommen. Trotzdem sollen die Fussnoten in den folgende Tabellen unter der jeweiligen Tabelle erscheinen:

\label{caseefothkabe}
\label{nominals-overview}
\label{perspron}
\label{interrog}
\label{indefpron-table}
\label{recogpron}
\label{caseformatives}
\label{frbearr}
\label{argalignverbs}

Dann machen wir das mit \multicol nach \lspbottomrule, wie in den folgenden Tabellen:

\label{kintermstable}
\label{intrinsicmiddleverbs}
\label{positional.verbs}
\label{pref.verbs}
