### ISSUE TITLE
gloss for \Third

### ISSUE THREAD

**Issue by chrdoe** [langsci/212#1285]
In der Glossierung für third person, erscheint die 3 tiefer gesetzt als die anderen Elemente. Das gilt nur für die 3, nicht für 1 firstperson oder 2 secondperson. Kann man das reparieren?

müsste das command \Third sein, auf jeden Fall in \Tsg, \Stsg, \Stnsg

**Comment by Glottotopia** [comment]
du kannst mal \oldstylenums an/ausmachen und schauen, was passiert
