### ISSUE TITLE
\fixgll

### ISSUE THREAD

**Issue by chrdoe** [langsci/212#1286]
Beim dreizeilligen Gloss (verbs in 03.tex, komplett 05.tex und komplett 06.tex) kommt es immer wieder zu Problemen mit Zeilenumbrüchen, die nicht gesetzt werden. Das hast du mit {\fixgll} elegant behoben. Ich habe das eher umständlich und brutal mit \sn gemacht. Dabei muss ich die komplette Struktur wiederholen (\glll, etc.). Allerdings gibt es bei deiner Methode etwas zu beachten: Der dreizeilige Gloss ist natürlich nur notwendig, wenn in einer Zeile ein Verb vorkommt. Falls es kein Verb gibt, reicht \gll statt \glll aus. Ich bin alle Beispiele durchgegangen und habe sie mit meiner Holzhackermethode entsprechend repariert. Wenn du daran etwas änderst, wenn du das wieder zurück zur {\fixgll}-Methode ändern solltest, wäre es wichtig darauf zu achten, dass es keine Zeilen mit dreizeiligem Gloss aber ohne Verb gibt. Denn sonst entsteht eine Leerzeile mitten Beispiel.

**Comment by Glottotopia** [comment]
Die Frage ist, ob das eine "meaningful absence" ist. Man kann für beide Varianten argumentieren. Ich bin aber leidenschaftslos

**Comment by chrdoe** [comment]
Das ist nie "meaningful", sondern immer ein Zufall des Zeilenumbruchs. Ich hab jetzt alle Zeilenumbrüche bei den dreizeiligen Glossen mit \sn "händisch" gemacht. (Und damit all deine \fixgll commands rausgehauen)
